# ~/.config/mpd/mpd.conf

music_directory     "/media/Storage/Music/Flac"

db_file             "~/.config/mpd/component/database"
playlist_directory  "~/.config/mpd/playlists"
state_file          "~/.config/mpd/component/state"
sticker_file        "~/.config/mpd/component/sticker.sql"
pid_file            "~/.config/mpd/component/pid"

log_file            "syslog"

auto_update         "yes"
auto_update_depth   "0"

bind_to_address     "~/.config/mpd/socket"

audio_buffer_size   "8192"
buffer_before_play  "10%"
max_playlist_length "16384"

decoder {
    plugin          "flac"
    enabled         "yes"
}

samplerate_converter "soxr very high"

audio_output {
    type            "pipewire"
    name            "MPD PipeWire Output"
    format          "44100:16:2"
    use_mmap        "yes"
    priority        "10"
}

audio_output {
    type            "fifo"
    name            "CAVA Visualizer"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}

follow_outside_symlinks     "yes"
follow_inside_symlinks      "yes"

metadata_to_use "artist,album,title,track,name,genre,date"