music_directory    "/media/Storage/Music/Flac"

db_file            "~/.config/mpd/database"
playlist_directory "~/.config/mpd/playlists"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"
pid_file	   	   "~/.config/mpd/pid"

log_file           "syslog"

auto_update "yes"
auto_update_depth "0"

bind_to_address    "~/.config/mpd/socket"

audio_output {
    type "pipewire"
    name "MPD PipeWire Output"
}

audio_output {
    type "fifo"
    name "CAVA Visualizer"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}

follow_outside_symlinks "yes"
follow_inside_symlinks "yes"
