# Default values are shown here, commented out.

[Connection]
# You can also export $MPD_HOST and/or $MPD_PORT to change the server.
host = /home/rimuren/.config/mpd/socket
port = 0
#password =

[Library]
music_dir = /media/Storage/Music/Flac
#cover_regex = ^(album|cover|\.?folder|front).*\.(gif|jpeg|jpg|png)$

[Bling]
mmkeys = False
notify = True
# Urgency of the notification: 0 for low, 1 for medium and 2 for high.
notify_urgency = 0

