# ╭───────────────────────────────╮
# │        STARSHIP CONFIG        │
# ╰───────────────────────────────╯

"$schema" = "https://starship.rs/config-schema.json"

# ─── General ────────────────────────────────────────────────────────────────

add_newline = true

format = """
$directory$fill$git_branch$cmd_duration$shell
$character"""

# ─── Shell ──────────────────────────────────────────────────────────────────

[shell]
disabled = false
format = "[$indicator]($style)"

bash_indicator = "󱆃 "
zsh_indicator  = "󰰶 "
fish_indicator = "󰈺 "

style = "fg:#B8C0FF"

[fill]
symbol = ' '

# ─── Directory ──────────────────────────────────────────────────────────────

[directory]
truncation_length = 4
truncation_symbol = "~/"
style = "fg:#7DCFFF"
format = " [$path]($style) "

[directory.substitutions]
"Developer" = "󰲋 "
"Documents" = "󰈙 "
"Downloads" = " "
"Music"      = " "
"Pictures"   = " "
"Desktop"    = " "
"Videos"     = " "
"Public"     = " "
"Templates"  = "󰈔 "

# ─── Git ────────────────────────────────────────────────────────────────────

[git_branch]
symbol = " "
style = "fg:#F0A6CA"
format = "[$symbol$branch]($style) "

# ─── Duration ───────────────────────────────────────────────────────────────

[cmd_duration]
min_time = 1000
style = "fg:#E6C384"
format = "[$duration]($style) "

# ─── Character ──────────────────────────────────────────────────────────────

[character]
success_symbol = "[ 󰘧](fg:#A6DA95)"
error_symbol = "[ 󰘧](fg:#E06C75)"
vimcmd_symbol = "[ 󰘧](fg:#8BD5CA)"
vimcmd_replace_one_symbol = "[ 󰘧](fg:#ED8796)"
vimcmd_visual_symbol = "[ 󰘧](fg:#B7BDF8)"

# ─── Transient ──────────────────────────────────────────────────────────────

[transience]
enabled = true